spring:
  application:
    name: Thortful
  datasource:
    url: jdbc:h2:mem:starwarsdb
    driverClassName: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
      path: ${SPRING_H2_CONSOLE_PATH:/h2-console}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
swapi:
  base-url: https://swapi.dev/api

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    api.challenge.thortful: ${LOGGING_LEVEL_API_CHALLENGE_THORTFUL:DEBUG}